version: "3.9"
services:
  frontend.vida-chile.local:
    container_name: frontend.vida-chile.local
    build:
      context: .
      dockerfile: build/Dockerfile.staging
    ports:
      - 44400:8080
    networks:
      - vida_chile_network

networks:
  vida_chile_network:
    external: true
