
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 15432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - vida_chile_network

networks:
  vida_chile_network:
    external: true

volumes:
  db_data:
    driver: local